//https://developer.arm.com/documentation/100166/0001/Programmers-Model/CortexM4-set-summary/Table-of-processor-CortexM4s?lang=en


#[derive(Clone,Debug)]

pub enum CortexM4 {
    MOVreg,
    MOVW,
    MOVT,
    MOVpc,
    ADDreg,
    ADDpc,
    ADC,
    ADR,
    SUB,
    SBC,
    RSB,
    MUL,
    MLA,
    MLS,
    SMULL,
    UMULL,
    SMLAL,
    UMLAL,
    SDIV,
    UDIV,
    SSAT,
    USAT,
    CMP,
    CMN,
    AND,
    EOR,
    ORR,
    ORN,
    BIC,
    MVN,
    TST,
    TEQ,
    LSL,
    LSR,
    ASR,
    ROR,
    RRX,
    CLZ,
    LDRreg,
    LDRpc,
    LDRH,
    LDRB,
    LDRSH,
    LDRSB,
    LDRT,
    LDRHT,
    LDRBT,
    LDRSHT,
    LDRSBT,
    LDRD,
    LDMreg,
    LDMpc,
    STR,
    STRH,
    STRB,
    STRSH,
    STRSB,
    STRT,
    STRHT,
    STRBT,
    STRSHT,
    STRSBT,
    STRD,
    STM,
    PUSH,
    POP,
    POPpc,
    LDREX,
    LDREXH,
    LDRREXB,
    STREX,
    STREXH,
    STREXB,
    CLREX,
    Bcc,//conditional branch
    B,
    BL,
    BX,
    BLX,
    CBZ,
    CBNZ,
    TBB,
    TBH,
    IT,
    CPSID,
    CPSIE,
    MRS,
    MSR,
    SXTH,
    SXTB,
    UXTH,
    UXTB,
    UBFX,
    SBFX,
    BFC,
    BFI,
    REV,
    REV16,
    REVSH,
    RBIT,
    SEV,
    WFE,
    WFI,
    NOP,
    ISB,
    DMB,
    DSB,
}

impl CortexM4 {
    pub fn getUpper(self, mut b:u32,n:u32,w:u32) -> u32 {
        let p=3;
        if b > p {
            b = p;
        }
        match self {
            CortexM4::MOVreg => 1,
            CortexM4::MOVW => 1,
            CortexM4::MOVT => 1,
            CortexM4::MOVpc => 1 + p,
            CortexM4::ADDreg => 1,
            CortexM4::ADDpc => 1 + p,
            CortexM4::ADC => 1,
            CortexM4::ADR => 1,
            CortexM4::SUB => 1,
            CortexM4::SBC => 1,
            CortexM4::RSB => 1,
            CortexM4::MUL => 1,
            CortexM4::MLA => 1,
            CortexM4::MLS => 1,
            CortexM4::SMULL => 1,
            CortexM4::UMULL => 1,
            CortexM4::SMLAL => 1,
            CortexM4::UMLAL => 1,
            CortexM4::SDIV => 12,
            CortexM4::UDIV => 12,
            CortexM4::SSAT => 1,
            CortexM4::USAT => 1,
            CortexM4::CMP => 1,
            CortexM4::CMN => 1,
            CortexM4::AND => 1,
            CortexM4::EOR => 1,
            CortexM4::ORR => 1,
            CortexM4::ORN => 1,
            CortexM4::BIC => 1,
            CortexM4::MVN => 1,
            CortexM4::TST => 1,
            CortexM4::TEQ => 1,
            CortexM4::LSL => 1,
            CortexM4::LSR => 1,
            CortexM4::ASR => 1,
            CortexM4::ROR => 1,
            CortexM4::RRX => 1,
            CortexM4::CLZ => 1,
            CortexM4::LDRreg => 2,
            CortexM4::LDRpc => 2 + p,
            CortexM4::LDRH => 2,
            CortexM4::LDRB => 2,
            CortexM4::LDRSH => 2,
            CortexM4::LDRSB => 2,
            CortexM4::LDRT => 2,
            CortexM4::LDRHT => 2,
            CortexM4::LDRBT => 2,
            CortexM4::LDRSHT => 2,
            CortexM4::LDRSBT => 2,
            CortexM4::LDRD => 1 + n,
            CortexM4::LDMreg => 1 + n,
            CortexM4::LDMpc => 1 + n + p,
            CortexM4::STR => 2,
            CortexM4::STRH => 2,
            CortexM4::STRB => 2,
            CortexM4::STRSH => 2,
            CortexM4::STRSB => 2,
            CortexM4::STRT => 2,
            CortexM4::STRHT => 2,
            CortexM4::STRBT => 2,
            CortexM4::STRSHT => 2,
            CortexM4::STRSBT => 2,
            CortexM4::STRD => 1 + n,
            CortexM4::STM => 1 + n,
            CortexM4::PUSH => 1 + n,
            CortexM4::POP => 1 + n,
            CortexM4::POPpc => 1 + n + p,
            CortexM4::LDREX => 2,
            CortexM4::LDREXH => 2,
            CortexM4::LDRREXB => 2,
            CortexM4::STREX => 2,
            CortexM4::STREXH => 2,
            CortexM4::STREXB => 2,
            CortexM4::CLREX => 1,
            CortexM4::Bcc => 1 + p,
            CortexM4::B => 1 + p,
            CortexM4::BL => 1 + p,
            CortexM4::BX => 1 + p,
            CortexM4::BLX => 1 + p,
            CortexM4::CBZ => 1 + p,
            CortexM4::CBNZ => 1 + p,
            CortexM4::TBB => 2 + p,
            CortexM4::TBH => 2 + p,
            CortexM4::IT => 1,
            CortexM4::CPSID => 2,
            CortexM4::CPSIE => 2,
            CortexM4::MRS => 2,
            CortexM4::MSR => 2,
            CortexM4::SXTH => 1,
            CortexM4::SXTB => 1,
            CortexM4::UXTH => 1,
            CortexM4::UXTB => 1,
            CortexM4::UBFX => 1,
            CortexM4::SBFX => 1,
            CortexM4::BFC => 1,
            CortexM4::BFI => 1,
            CortexM4::REV => 1,
            CortexM4::REV16 => 1,
            CortexM4::REVSH => 1,
            CortexM4::RBIT => 1,
            CortexM4::SEV => 1,
            CortexM4::WFE => 1 + w,
            CortexM4::WFI => 1 + w,
            CortexM4::NOP => 1,
            CortexM4::ISB => 1 + b,
            CortexM4::DMB => 1 + b,
            CortexM4::DSB => 1 + b,
        }
    }

    pub fn getLower(self, b:u32,n:u32,w:u32) -> u32 {
        let p=1;
        match self {
            CortexM4::MOVreg => 1,
            CortexM4::MOVW => 1,
            CortexM4::MOVT => 1,
            CortexM4::MOVpc => 1 + p,
            CortexM4::ADDreg => 1,
            CortexM4::ADDpc => 1 + p,
            CortexM4::ADC => 1,
            CortexM4::ADR => 1,
            CortexM4::SUB => 1,
            CortexM4::SBC => 1,
            CortexM4::RSB => 1,
            CortexM4::MUL => 1,
            CortexM4::MLA => 1,
            CortexM4::MLS => 1,
            CortexM4::SMULL => 1,
            CortexM4::UMULL => 1,
            CortexM4::SMLAL => 1,
            CortexM4::UMLAL => 1,
            CortexM4::SDIV => 2,
            CortexM4::UDIV => 2,
            CortexM4::SSAT => 1,
            CortexM4::USAT => 1,
            CortexM4::CMP => 1,
            CortexM4::CMN => 1,
            CortexM4::AND => 1,
            CortexM4::EOR => 1,
            CortexM4::ORR => 1,
            CortexM4::ORN => 1,
            CortexM4::BIC => 1,
            CortexM4::MVN => 1,
            CortexM4::TST => 1,
            CortexM4::TEQ => 1,
            CortexM4::LSL => 1,
            CortexM4::LSR => 1,
            CortexM4::ASR => 1,
            CortexM4::ROR => 1,
            CortexM4::RRX => 1,
            CortexM4::CLZ => 1,
            CortexM4::LDRreg => 2,
            CortexM4::LDRpc => 2 + p,
            CortexM4::LDRH => 2,
            CortexM4::LDRB => 2,
            CortexM4::LDRSH => 2,
            CortexM4::LDRSB => 2,
            CortexM4::LDRT => 2,
            CortexM4::LDRHT => 2,
            CortexM4::LDRBT => 2,
            CortexM4::LDRSHT => 2,
            CortexM4::LDRSBT => 2,
            CortexM4::LDRD => 1 + n,
            CortexM4::LDMreg => 1 + n,
            CortexM4::LDMpc => 1 + n + p,
            CortexM4::STR => 2,
            CortexM4::STRH => 2,
            CortexM4::STRB => 2,
            CortexM4::STRSH => 2,
            CortexM4::STRSB => 2,
            CortexM4::STRT => 2,
            CortexM4::STRHT => 2,
            CortexM4::STRBT => 2,
            CortexM4::STRSHT => 2,
            CortexM4::STRSBT => 2,
            CortexM4::STRD => 1 + n,
            CortexM4::STM => 1 + n,
            CortexM4::PUSH => 1 + n,
            CortexM4::POP => 1 + n,
            CortexM4::POPpc => 1 + n + p,
            CortexM4::LDREX => 2,
            CortexM4::LDREXH => 2,
            CortexM4::LDRREXB => 2,
            CortexM4::STREX => 2,
            CortexM4::STREXH => 2,
            CortexM4::STREXB => 2,
            CortexM4::CLREX => 1,
            CortexM4::Bcc => 1,
            CortexM4::B => 1 + p,
            CortexM4::BL => 1 + p,
            CortexM4::BX => 1 + p,
            CortexM4::BLX => 1 + p,
            CortexM4::CBZ => 1,
            CortexM4::CBNZ => 1,
            CortexM4::TBB => 2 + p,
            CortexM4::TBH => 2 + p,
            CortexM4::IT => 1,
            CortexM4::CPSID => 1,
            CortexM4::CPSIE => 1,
            CortexM4::MRS => 1,
            CortexM4::MSR => 1,
            CortexM4::SXTH => 1,
            CortexM4::SXTB => 1,
            CortexM4::UXTH => 1,
            CortexM4::UXTB => 1,
            CortexM4::UBFX => 1,
            CortexM4::SBFX => 1,
            CortexM4::BFC => 1,
            CortexM4::BFI => 1,
            CortexM4::REV => 1,
            CortexM4::REV16 => 1,
            CortexM4::REVSH => 1,
            CortexM4::RBIT => 1,
            CortexM4::SEV => 1,
            CortexM4::WFE => 1 + w,
            CortexM4::WFI => 1 + w,
            CortexM4::NOP => 1,
            CortexM4::ISB => 1 + b,
            CortexM4::DMB => 1 + b,
            CortexM4::DSB => 1 + b,
        }
    }
}