[package]
name = "cortex-klee-tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
regex = "1.5.4"
clap = "3.1.6"
rustc-demangle = "0.1.21"